CREATE DATABASE EXAMEN_FINAL
GO
USE EXAMEN_FINAL
GO

CREATE TABLE USERS(
ID_USER INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
PROFILE_PICTURE VARCHAR(1000) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
USERNAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL
)

CREATE TABLE POST(
ID_POST INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
TITLE VARCHAR(50) NOT NULL,
CAPTION VARCHAR(50) NOT NULL,
TIMEDATE VARCHAR(100) NOT NULL,
ID_USER INT FOREIGN KEY REFERENCES USERS(ID_USER) ON DELETE CASCADE NOT NULL,
VISIBLE BIT NOT NULL
)